name: Watch KernelSU
on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check for new KernelSU release
        id: check_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/rsuntk/KernelSU/releases/latest" | jq -r .tag_name)
          CURRENT_RELEASE=$(cat ksu_version.txt 2>/dev/null || echo "")
          if [ "$LATEST_RELEASE" != "$CURRENT_RELEASE" ]; then
            echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
            echo "UPDATE_KERNELSU=true" >> $GITHUB_ENV
          else
            echo "UPDATE_KERNELSU=false" >> $GITHUB_ENV
          fi

          LATEST_NEXT_RELEASE=$(curl --silent "https://api.github.com/repos/rifsxd/KernelSU/releases/latest" | jq -r .tag_name)
          CURRENT_NEXT_RELEASE=$(cat ksu_next_version.txt 2>/dev/null || echo "")
          if [ "$LATEST_NEXT_RELEASE" != "$CURRENT_NEXT_RELEASE" ]; then
            echo "LATEST_NEXT_RELEASE=$LATEST_NEXT_RELEASE" >> $GITHUB_ENV
            echo "UPDATE_NEXT_KERNELSU=true" >> $GITHUB_ENV
          else
            echo "UPDATE_NEXT_KERNELSU=false" >> $GITHUB_ENV
          fi

      - name: Create file with KernelSU version
        if: env.UPDATE_KERNELSU == 'true'
        run: echo "${{ env.LATEST_RELEASE }}" > ksu_version.txt

      - name: Create file with KernelSU next version
        if: env.UPDATE_NEXT_KERNELSU == 'true'
        run: echo "${{ env.LATEST_NEXT_RELEASE }}" > ksu_next_version.txt

      - name: Commit and push changes
        if: env.UPDATE_KERNELSU == 'true' || env.UPDATE_NEXT_KERNELSU == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ksu_version.txt ksu_next_version.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update to latest KernelSU release tags" && git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${GITHUB_REF#refs/heads/})

      - name: Trigger Build Kernel workflow
        if: env.UPDATE_KERNELSU == 'true' || env.UPDATE_NEXT_KERNELSU == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            event-type: trigger-KernelSU-build
  
      - name: Log successful dispatch
        if: env.UPDATE_KERNELSU == 'true' || env.UPDATE_NEXT_KERNELSU == 'true'
        run: echo "Repository dispatch event triggered successfully for KernelSU build."
  